"""library_model

Revision ID: 007
Revises: 006
Create Date: 2025-02-14 15:06:52.412674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('_intid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), sa.Computed("'LIB' || _intid", ), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_intid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('library_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('library_collections',
    sa.Column('_intid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), sa.Computed("'C' || _intid", ), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['library_collections.id'], ),
    sa.PrimaryKeyConstraint('_intid'),
    sa.UniqueConstraint('id')
    )
    op.create_table('library_items',
    sa.Column('_intid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), sa.Computed("'L' || _intid", ), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['library_collections.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('_intid'),
    sa.UniqueConstraint('id')
    )
    op.create_table('library_item_tags',
    sa.Column('library_item_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_item_id'], ['library_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['library_tags.id'], )
    )
    op.create_table('library_item_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['library_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_item_versions')
    op.drop_table('library_item_tags')
    op.drop_table('library_items')
    op.drop_table('library_collections')
    op.drop_table('library_tags')
    op.drop_table('libraries')
    # ### end Alembic commands ###
