"""Add Workflow Schedules

Revision ID: 011
Revises: 010_add_idx_to_time_cols
Create Date: 2023-07-13 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "011"
down_revision = "010_add_idx_to_time_cols"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_schedules",
        sa.Column("_intid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cron_expression", sa.String(), nullable=False),
        sa.Column("initial_inputs", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, default=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("_intid"),
        sa.UniqueConstraint("id"),
    )

    op.create_index(
        op.f("ix_workflow_schedules_created_at"),
        "workflow_schedules",
        ["created_at"],
        unique=False,
    )

    op.create_index(
        op.f("ix_workflow_schedules_workflow_id"),
        "workflow_schedules",
        ["workflow_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_schedules_workflow_id"), table_name="workflow_schedules")
    op.drop_index(op.f("ix_workflow_schedules_created_at"), table_name="workflow_schedules")
    op.drop_table("workflow_schedules")
    # ### end Alembic commands ###
